brew "stow"

brew "neovim"
brew "tmux"

cask "raycast"
cask "ghostty"
cask "orbstack"
cask "zen"
cask "google-chrome"
cask "visual-studio-code"
cask "insomnia"
cask "obsidian"
cask "telegram"
cask "discord"
cask "iina"
cask "readdle-spark"
cask "tailscale-app"
cask "transmission"
cask "omnidisksweeper"
cask "betterdisplay"
cask "mac-mouse-fix"
cask "appcleaner"
cask "coconutbattery"
cask "keka"
cask "utm"
cask "tableplus"